/**
 * States in the Browser Agent lifecycle.
 */
export enum AgentState {
  /** Task received, not yet started */
  New = 'new',
  /** Model Gateway is generating a plan */
  Planning = 'planning',
  /** Policy Engine is checking authorization */
  Authorizing = 'authorizing',
  /** Execution Runtime is running browser actions */
  Executing = 'executing',
  /** Verification Layer is checking results */
  Verifying = 'verifying',
  /** Task completed successfully */
  Success = 'success',
  /** Verification failed, replanning with memory context */
  Replanning = 'replanning',
  /** Task failed after all retries */
  Failed = 'failed',
}

/**
 * High-level browser actions the planner can emit.
 *
 * The planner reasons about intent. The runtime translates
 * these into Playwright (or other automation) operations.
 */
export type BrowserAction =
  | { type: 'open'; url: string }
  | { type: 'click'; selector: string }
  | { type: 'type'; selector: string; text: string }
  | { type: 'extract'; selector: string; attribute?: string }
  | { type: 'search'; query: string }
  | { type: 'wait'; condition: WaitCondition }
  | { type: 'screenshot'; label?: string }
  | { type: 'scroll'; direction: 'up' | 'down'; amount?: number }
  | { type: 'navigate'; direction: 'back' | 'forward' }
  | { type: 'assert'; selector: string; expected: string };

/**
 * Conditions for the wait action.
 */
export type WaitCondition =
  | { kind: 'selector'; selector: string }
  | { kind: 'navigation' }
  | { kind: 'timeout'; ms: number };

/**
 * A plan generated by the Model Gateway for a browser task.
 */
export interface BrowserPlan {
  /** Ordered list of actions to execute */
  actions: BrowserAction[];
  /** Human-readable reasoning for the plan */
  reasoning: string;
}

/**
 * Result of executing a single browser action.
 */
export interface ActionResult {
  /** The action that was executed */
  action: BrowserAction;
  /** Whether it succeeded */
  success: boolean;
  /** Extracted value (for extract/assert actions) */
  value?: string;
  /** Error message if failed */
  error?: string;
  /** Duration in ms */
  durationMs: number;
  /** Screenshot path (for screenshot actions) */
  screenshot?: string;
}

/**
 * Result of the complete browser agent execution.
 */
export interface AgentResult {
  /** Final state */
  state: AgentState;
  /** Whether the task succeeded */
  success: boolean;
  /** Collected action results */
  actions: ActionResult[];
  /** Extracted data from the task */
  data: Record<string, string>;
  /** Error if failed */
  error?: string;
  /** Total duration in ms */
  durationMs: number;
  /** Number of plan attempts */
  planAttempts: number;
}

/**
 * A browser task request.
 */
export interface BrowserTask {
  /** Human-readable description of what to accomplish */
  description: string;
  /** Starting URL (optional) */
  startUrl?: string;
  /** Expected output schema (what data to extract) */
  expectedOutput?: Record<string, string>;
  /** Maximum plan attempts before failing */
  maxAttempts?: number;
  /** Abort signal */
  signal?: AbortSignal;
}

/**
 * Interface for the browser runtime that executes actions.
 *
 * This abstracts away Playwright (or any other automation library).
 * The agent state machine and planner never import Playwright directly.
 */
export interface BrowserRuntime {
  /** Execute a single browser action */
  execute(action: BrowserAction): Promise<ActionResult>;
  /** Get the current page URL */
  currentUrl(): Promise<string>;
  /** Get the current page title */
  pageTitle(): Promise<string>;
  /** Close the browser */
  close(): Promise<void>;
}

/**
 * Interface for the planner that generates browser action plans.
 *
 * In production, this calls the Model Gateway.
 * In tests, a stub can return deterministic plans.
 */
export interface BrowserPlanner {
  /** Generate an initial plan for a task */
  plan(task: BrowserTask): Promise<BrowserPlan>;
  /** Replan after a verification failure, using memory of what was tried */
  replan(task: BrowserTask, previousActions: ActionResult[], failureReason: string): Promise<BrowserPlan>;
}

/**
 * Interface for authorizing browser actions via the Policy Engine.
 */
export interface BrowserAuthorizer {
  /** Check if a plan is authorized to execute */
  authorize(task: BrowserTask, plan: BrowserPlan): Promise<AuthorizationResult>;
}

/**
 * Result of an authorization check.
 */
export interface AuthorizationResult {
  /** Whether execution is authorized */
  authorized: boolean;
  /** Reason (if denied) */
  reason?: string;
  /** Whether human override is possible */
  overridable: boolean;
}

/**
 * Interface for verifying browser task results.
 */
export interface BrowserVerifier {
  /** Verify that the task output matches expectations */
  verify(task: BrowserTask, actions: ActionResult[]): Promise<VerifyResult>;
}

/**
 * Result of verification.
 */
export interface VerifyResult {
  /** Whether verification passed */
  passed: boolean;
  /** Extracted data that was verified */
  data: Record<string, string>;
  /** Reason for failure (if failed) */
  reason?: string;
}
